from __future__ import annotations
import argparse


def add_sign_layout_args(parser: argparse.ArgumentParser) -> None:
    """Add inline-sign layout arguments shared by document workflow commands."""
    parser.add_argument("--sign-input")
    parser.add_argument("--sign-output")
    parser.add_argument("--sign-signature-png")
    parser.add_argument("--sign-page", type=int, default=0)
    parser.add_argument("--sign-x", type=float, default=0.0)
    parser.add_argument("--sign-y", type=float, default=0.0)
    parser.add_argument("--sign-width", type=float, default=0.0)
    parser.add_argument("--sign-show-signature", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--sign-show-name", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--sign-show-date", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--sign-name-text")
    parser.add_argument("--sign-date-text")
    parser.add_argument("--date-format", default="%Y-%m-%d")
    parser.add_argument("--sign-name-pos", choices=["above", "below", "off"], default="above")
    parser.add_argument("--sign-date-pos", choices=["above", "below", "off"], default="below")
    parser.add_argument("--sign-name-size", type=int, default=12)
    parser.add_argument("--sign-date-size", type=int, default=12)
    parser.add_argument("--sign-color", default="#000000")
    parser.add_argument("--sign-name-above", type=float, default=6.0)
    parser.add_argument("--sign-name-below", type=float, default=12.0)
    parser.add_argument("--sign-date-above", type=float, default=18.0)
    parser.add_argument("--sign-date-below", type=float, default=24.0)
    parser.add_argument("--sign-x-offset", type=float, default=0.0)
    parser.add_argument("--signer-password")
    parser.add_argument("--sign-mode", choices=["visual", "crypto", "both"], default="visual")
    parser.add_argument("--sign-dry-run", action="store_true")
    parser.add_argument("--sign-overwrite-output", action="store_true")


def register_signature_parsers(sub: argparse._SubParsersAction) -> None:
    # Top-level sign-visual command
    sign_parser = sub.add_parser("sign-visual", help="Visual PDF signing with fixed position")
    sign_parser.add_argument("--input", required=True)
    sign_parser.add_argument("--output")
    sign_parser.add_argument("--signature-png")
    sign_parser.add_argument("--page", type=int, default=0)
    sign_parser.add_argument("--x", type=float, required=True)
    sign_parser.add_argument("--y", type=float, required=True)
    sign_parser.add_argument("--width", type=float, required=True)
    sign_parser.add_argument("--show-signature", action=argparse.BooleanOptionalAction, default=True)
    sign_parser.add_argument("--show-name", action=argparse.BooleanOptionalAction, default=True)
    sign_parser.add_argument("--show-date", action=argparse.BooleanOptionalAction, default=True)
    sign_parser.add_argument("--name-text")
    sign_parser.add_argument("--date-text")
    sign_parser.add_argument("--date-format", default="%Y-%m-%d")
    sign_parser.add_argument("--name-pos", choices=["above", "below", "off"], default="above")
    sign_parser.add_argument("--date-pos", choices=["above", "below", "off"], default="below")
    sign_parser.add_argument("--name-size", type=int, default=12)
    sign_parser.add_argument("--date-size", type=int, default=12)
    sign_parser.add_argument("--color", default="#000000")
    sign_parser.add_argument("--name-above", type=float, default=6.0)
    sign_parser.add_argument("--name-below", type=float, default=12.0)
    sign_parser.add_argument("--date-above", type=float, default=18.0)
    sign_parser.add_argument("--date-below", type=float, default=24.0)
    sign_parser.add_argument("--x-offset", type=float, default=0.0)
    sign_parser.add_argument("--signer-user", required=True)
    sign_parser.add_argument("--password")
    sign_parser.add_argument("--reason", default="cli")
    sign_parser.add_argument("--mode", choices=["visual", "crypto", "both"], default="visual")
    sign_parser.add_argument("--dry-run", action="store_true")
    sign_parser.add_argument("--overwrite-output", action="store_true")

    # sign group with subcommands
    sign_group = sub.add_parser("sign", help="Signature operations")
    sign_sub = sign_group.add_subparsers(dest="sign_command", required=True)

    sign_visual = sign_sub.add_parser("visual", help="Visual PDF signing with fixed position")
    sign_visual.add_argument("--input", required=True)
    sign_visual.add_argument("--output")
    sign_visual.add_argument("--signature-png")
    sign_visual.add_argument("--page", type=int, default=0)
    sign_visual.add_argument("--x", type=float, required=True)
    sign_visual.add_argument("--y", type=float, required=True)
    sign_visual.add_argument("--width", type=float, required=True)
    sign_visual.add_argument("--show-signature", action=argparse.BooleanOptionalAction, default=True)
    sign_visual.add_argument("--show-name", action=argparse.BooleanOptionalAction, default=True)
    sign_visual.add_argument("--show-date", action=argparse.BooleanOptionalAction, default=True)
    sign_visual.add_argument("--name-text")
    sign_visual.add_argument("--date-text")
    sign_visual.add_argument("--date-format", default="%Y-%m-%d")
    sign_visual.add_argument("--name-pos", choices=["above", "below", "off"], default="above")
    sign_visual.add_argument("--date-pos", choices=["above", "below", "off"], default="below")
    sign_visual.add_argument("--name-size", type=int, default=12)
    sign_visual.add_argument("--date-size", type=int, default=12)
    sign_visual.add_argument("--color", default="#000000")
    sign_visual.add_argument("--name-above", type=float, default=6.0)
    sign_visual.add_argument("--name-below", type=float, default=12.0)
    sign_visual.add_argument("--date-above", type=float, default=18.0)
    sign_visual.add_argument("--date-below", type=float, default=24.0)
    sign_visual.add_argument("--x-offset", type=float, default=0.0)
    sign_visual.add_argument("--signer-user", required=True)
    sign_visual.add_argument("--password")
    sign_visual.add_argument("--reason", default="cli")
    sign_visual.add_argument("--mode", choices=["visual", "crypto", "both"], default="visual")
    sign_visual.add_argument("--dry-run", action="store_true")
    sign_visual.add_argument("--overwrite-output", action="store_true")

    sign_import_asset = sign_sub.add_parser("import-asset", help="Import PNG/GIF signature asset securely")
    sign_import_asset.add_argument("--owner-user-id", required=True)
    sign_import_asset.add_argument("--input", required=True)

    sign_import_set_active = sign_sub.add_parser("import-set-active", help="Import signature asset and set as active")
    sign_import_set_active.add_argument("--owner-user-id", required=True)
    sign_import_set_active.add_argument("--input", required=True)
    sign_import_set_active.add_argument("--password")

    sign_template_create = sign_sub.add_parser("template-create", help="Create user signature template")
    sign_template_create.add_argument("--owner-user-id", required=True)
    sign_template_create.add_argument("--name", required=True)
    sign_template_create.add_argument("--scope", choices=["user", "global"], default="user")
    sign_template_create.add_argument("--asset-id")
    sign_template_create.add_argument("--page", type=int, default=0)
    sign_template_create.add_argument("--x", type=float, required=True)
    sign_template_create.add_argument("--y", type=float, required=True)
    sign_template_create.add_argument("--width", type=float, required=True)
    sign_template_create.add_argument("--show-signature", action=argparse.BooleanOptionalAction, default=True)
    sign_template_create.add_argument("--show-name", action=argparse.BooleanOptionalAction, default=True)
    sign_template_create.add_argument("--show-date", action=argparse.BooleanOptionalAction, default=True)
    sign_template_create.add_argument("--name-text")
    sign_template_create.add_argument("--date-text")
    sign_template_create.add_argument("--name-pos", choices=["above", "below", "off"], default="above")
    sign_template_create.add_argument("--date-pos", choices=["above", "below", "off"], default="below")
    sign_template_create.add_argument("--name-size", type=int, default=12)
    sign_template_create.add_argument("--date-size", type=int, default=12)
    sign_template_create.add_argument("--color", default="#000000")
    sign_template_create.add_argument("--name-above", type=float, default=6.0)
    sign_template_create.add_argument("--name-below", type=float, default=12.0)
    sign_template_create.add_argument("--date-above", type=float, default=18.0)
    sign_template_create.add_argument("--date-below", type=float, default=24.0)
    sign_template_create.add_argument("--x-offset", type=float, default=0.0)

    sign_template_update = sign_sub.add_parser("template-update", help="Update an existing signature template")
    sign_template_update.add_argument("--template-id", required=True)
    sign_template_update.add_argument("--owner-user-id", required=True)
    sign_template_update.add_argument("--name")
    sign_template_update.add_argument("--asset-id")
    sign_template_update.add_argument("--page", type=int)
    sign_template_update.add_argument("--x", type=float)
    sign_template_update.add_argument("--y", type=float)
    sign_template_update.add_argument("--width", type=float)
    sign_template_update.add_argument("--show-signature", action=argparse.BooleanOptionalAction, default=None)
    sign_template_update.add_argument("--show-name", action=argparse.BooleanOptionalAction, default=None)
    sign_template_update.add_argument("--show-date", action=argparse.BooleanOptionalAction, default=None)
    sign_template_update.add_argument("--name-text")
    sign_template_update.add_argument("--date-text")
    sign_template_update.add_argument("--name-pos", choices=["above", "below", "off"], default="above")
    sign_template_update.add_argument("--date-pos", choices=["above", "below", "off"], default="below")
    sign_template_update.add_argument("--name-size", type=int, default=12)
    sign_template_update.add_argument("--date-size", type=int, default=12)
    sign_template_update.add_argument("--color", default="#000000")
    sign_template_update.add_argument("--name-above", type=float, default=6.0)
    sign_template_update.add_argument("--name-below", type=float, default=12.0)
    sign_template_update.add_argument("--date-above", type=float, default=18.0)
    sign_template_update.add_argument("--date-below", type=float, default=24.0)
    sign_template_update.add_argument("--x-offset", type=float, default=0.0)

    sign_template_list = sign_sub.add_parser("template-list", help="List user signature templates")
    sign_template_list.add_argument("--owner-user-id", required=False, default="")
    sign_template_list.add_argument("--scope", choices=["user", "global"], default="user")

    sign_template_delete = sign_sub.add_parser("template-delete", help="Delete signature template")
    sign_template_delete.add_argument("--template-id", required=True)

    sign_template_copy_global = sign_sub.add_parser("template-copy-global", help="Copy global template to user")
    sign_template_copy_global.add_argument("--template-id", required=True)
    sign_template_copy_global.add_argument("--owner-user-id", required=True)
    sign_template_copy_global.add_argument("--name")

    sign_active_set = sign_sub.add_parser("active-set", help="Set active signature asset")
    sign_active_set.add_argument("--owner-user-id", required=True)
    sign_active_set.add_argument("--asset-id", required=True)
    sign_active_set.add_argument("--password")

    sign_active_get = sign_sub.add_parser("active-get", help="Get active signature asset")
    sign_active_get.add_argument("--owner-user-id", required=True)

    sign_active_clear = sign_sub.add_parser("active-clear", help="Clear active signature asset")
    sign_active_clear.add_argument("--owner-user-id", required=True)
    sign_active_clear.add_argument("--password")

    sign_active_export = sign_sub.add_parser("active-export", help="Export active signature asset")
    sign_active_export.add_argument("--owner-user-id", required=True)
    sign_active_export.add_argument("--output", required=True)

    sign_template_sign = sign_sub.add_parser("template-sign", help="Sign using stored template")
    sign_template_sign.add_argument("--template-id", required=True)
    sign_template_sign.add_argument("--input", required=True)
    sign_template_sign.add_argument("--output")
    sign_template_sign.add_argument("--signer-user", required=True)
    sign_template_sign.add_argument("--password")
    sign_template_sign.add_argument("--reason", default="template_cli")
    sign_template_sign.add_argument("--dry-run", action="store_true")
    sign_template_sign.add_argument("--overwrite-output", action="store_true")

